# Generated by Django 6.0.3 on 2026-04-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("upcoming", "Upcoming"),
                    ("urgent", "Urgent"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
